targets:
  $default:
    builders:
      envied_generator|envied:
        enabled: True
        options:
          env_file: .env
builders:
  envied:
    import: "package:envied_generator/builder.dart"
    builder_factories: ["enviedBuilder"]
    build_extensions:
      .dart:
        - envied.g.dart
    build_to: cache
    auto_apply: dependents
    applies_builders: ["source_gen|combining_builder"]
